### ISSUE TITLE
GooglePlus native extension is not supported on this platform.

### ISSUE THREAD

**Issue by anhtran1989** [DaVikingCode/GooglePlus-ANE#1]
Hi Daviking, today i use GooglePlus-ANE, i use starling framework, but when create GooglePlus have bug "GooglePlus native extension is not supported on this platform.". Can you answer help me why bug and solution fix. Thanks you :D

**Comment by alamboley** [comment]
Hi, on which platform are you testing ? Which device ?

**Comment by anhtran1989** [comment]
I use Iphone 5s :D, but i haven't buy 15$ ( https://gumroad.com/l/GooglePlus-ANE ) :D. Can buy apps run? Sorry my english is bad :(

**Comment by alamboley** [comment]
You must buy a license to have the rights to use this ANE.

**Comment by anhtran1989** [comment]
Hi, thanks you :D

**Comment by alamboley** [comment]
Buying the license you will get the ANE file. It can't work without it.
