### ISSUE TITLE
IOS Safari could not open Site

### ISSUE THREAD

**Issue by railnation** [DaVikingCode/GooglePlus-ANE#2]
Hi, 

I use the ANE for the IOS Google+ Login. If I try to sign in Safari opens the Google Plus authorization. After I click on Accept button the next page could not be loaded. 

Safari tells that this Website is invalid. 

Can you help me?

**Comment by alamboley** [comment]
Hey, what device are you using? Which iOS version?

**Comment by railnation** [comment]
IPhone 6, 8.4

**Comment by alamboley** [comment]
Hmm I'm using the latest iOS version, tested on an iPhone 4S and iPad 3 and both works fine... Are you on a special network? Also if you install the G+ app on your iPhone does the ANE works fine?

**Comment by railnation** [comment]
No I am not on a special network. I updated my Iphone 6 to 8.4.1 and installed G+ App. Both wont work.

**Comment by alamboley** [comment]
Are you again using your own code? Does the demo works? Do you have any others ANE in your project?

**Comment by railnation** [comment]
Yes, but why, this code is not so far away from your sample. If I try to sign in no event will be dispatch. It tries so login opens, browser or g+ app and then nothing happens. 

Yes I use some distriqt native extensions.

**Comment by alamboley** [comment]
Does the demo code works even with the distriqt native extensions used?

**Comment by railnation** [comment]
So, I used your demo code for quick test. I removed all other Extensions, same result. both (g+ app or browser does not trigger the loggin success.

**Comment by alamboley** [comment]
Do you have specified the `CFBundleURLTypes` in the `*-app.xml` with your app id? See the instructions.pdf file.

**Comment by railnation** [comment]
<key>CFBundleURLTypes</key>
        <array>
            <dict>
                <key>CFBundleURLSchemes</key>
                <array>
                    <string>com.traviangames.railnation</string>
		      		<string>fbXXXXXXXXXXXX</string>
                </array>
                <key>CFBundleURLName</key>
                <string>com.traviangames.railnation</string>
            </dict>
        </array>

you mean that one?

**Comment by alamboley** [comment]
Yep, do you see any change if you simplify it to:
```xml
<key>CFBundleURLTypes</key>
        <array>
            <dict>
                <key>CFBundleURLSchemes</key>
                <array>
                    <string>com.traviangames.railnation</string>
                </array>
            </dict>
        </array>
```

Also be sure UIApplicationExitsOnSuspend is set to false in the *-app.xml. Otherwise it will leave the app and it won’t save that you already logged in.

**Comment by railnation** [comment]
honestly same result as before.

**Comment by alamboley** [comment]
Could you send me a mail to the adress mentionned in the PDF with your project simplified. I mean with strictly the minimum to test the ANE.

**Comment by railnation** [comment]
I dont have any pdf file in the zip :(

**Comment by alamboley** [comment]
It is in the docs folder. Which mail did you use to buy the ANE?
