### ISSUE TITLE
Android application crash

### ISSUE THREAD

**Issue by railnation** [DaVikingCode/GooglePlus-ANE#3]
Hi, 

If I try to sign in with Google+ on Android my application crahes. 

LogCat: 

09-03 13:29:33.556: E/GetGooglePlusToken(16170): UserRecoverableAuthException
09-03 13:29:33.557: A/GetGooglePlusToken(16170): Code should not go here

**Comment by alamboley** [comment]
Hey, are you trying with the code demo or your own?

**Comment by railnation** [comment]
Hi, my own code.

**Comment by alamboley** [comment]
Could you copy/paste it here?

**Comment by railnation** [comment]
public function init(googleClientID : String) : void
		{
			if (mGooglePlus == null)
			{
				mClientID = googleClientID;
				mGooglePlus = new GooglePlus();

				registerEventListener(mGooglePlus, GooglePlusEvent.LOGIN_SUCCESSED, onLoginSuccess);
				registerEventListener(mGooglePlus, GooglePlusEvent.LOGIN_FAILED, onLoginFailed);
				registerEventListener(mGooglePlus, GooglePlusEvent.USER_INFO, onUserInfo);
				registerEventListener(mGooglePlus, GooglePlusEvent.DISCONNECTED, onDisconnected);
				registerEventListener(mGooglePlus, GooglePlusEvent.TOKEN, onToken);
			}
	}

	public function login() : void
	{
		if (!mGooglePlus.isAuthenticated())
		{
			mGooglePlus.login(mClientID);
		}
		else
		{
			mGooglePlus.getAuth();
		}
	}

	private function onLoginSuccess(gpEvt : GooglePlusEvent) : void
	{
		trace("login successed");
		mGooglePlus.getUserInfo();
	}

	private function onLoginFailed(gpEvt : GooglePlusEvent) : void
	{
		trace("login failed");
		dispatchEvent(new ParameterEvent(LOGIN_FAILED));
	}

	private function onToken(gpEvt : GooglePlusEvent) : void
	{
		trace("token: " + gpEvt.informations);
		mAccessToken = gpEvt.informations;
		onTokenReceived(mAccessToken);

		if (!mGooglePlus.isAuthenticated())
		{
			mGooglePlus.login(mClientID, true);
		}
	}

	protected function onTokenReceived(token : String) : void
	{
		trace("onTokenReceived: " + token);
		dispatchEvent(new ParameterEvent(LOGIN_TOKEN, token));
	}

	private function onDisconnected(gpEvt : GooglePlusEvent) : void
	{
		trace("disconnected from google plus");
	}

	private function onUserInfo(gpEvt : GooglePlusEvent) : void
	{
		trace("userInfo: " + gpEvt.informations);
		mGooglePlus.getAuth();
	}

	public function getAccessToken() : String
	{
		return mAccessToken;
	}

**Comment by alamboley** [comment]
Could you remove the `getAuth`call? It can only be called if the user is authenticated.

**Comment by railnation** [comment]
Yes I did that. If the Method onUserInfo is called the app crahes

login successed
userInfo: {"image":{"url":"https://lh3.googleusercontent.com/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg?sz=50"},"url":"https://plus.google.com/103543759283408026173","objectType":"person","circledByCount":0,"displayName":"Bright Future","isPlusUser":true,"verified":false,"id":"103543759283408026173","name":{"familyName":"Future","givenName":"Bright"}}

**Comment by alamboley** [comment]
In many cases, you don't need the token, unless you want to connect to an other service. Do you really need to call mGooglePlus.getAuth(); ? Again it isn't to authenticate the user, but to access it's GTMOAuth2Authentication #c42fe482d61f1f63b4f2550d580880c738bea1e0

**Comment by railnation** [comment]
I need the user token for G+ for registering or login with our user system.

**Comment by alamboley** [comment]
Ok, could you try exactly my demo and see if you have also the problem? Thanks.

**Comment by railnation** [comment]
yes I try tomorrow :)

**Comment by railnation** [comment]
mGooglePlus.login(mClientID, true); works on my Android test device.

**Comment by alamboley** [comment]
Undeed make sense, you need extended set up to true to have user's ID etc.
